-- Suppression des tables (à exécuter avant la création)

DROP TABLE IF EXISTS CUI_ETIQUETTAGE;
DROP TABLE IF EXISTS CUI_COMPOSITION;
DROP TABLE IF EXISTS CUI_RECETTE;
DROP TABLE IF EXISTS CUI_INGREDIENT;
DROP TABLE IF EXISTS CUI_CATEGORIE;
DROP TABLE IF EXISTS CUI_UTILISATEUR;
DROP TABLE IF EXISTS CUI_TAG;